# This configuration file tells Netlify how to build and deploy the Python function.

[build]
  # This command tells Netlify to install the Python packages listed in requirements.txt.
  command = "pip install -r requirements.txt"
  # The directory where your public files (index.html) are located.
  publish = "/"

[functions]
  # The directory where our Python serverless function is located.
  directory = "netlify/functions"
  # We need to include the installed packages in our function bundle.
  included_files = ["!**/*.node"]

